---
title: "Leslies_Matrix_Pratice"
format: html
editor: visual
---

## Matrices

```{r}
# make a sequence of values from 1 to 10
my_values <- seq(from = 1, to = 10, by = 1)

#look at my valies (always!)
```


```{r}
# convert to matrix 
my_matrix <- matrix(data = my_values, 
                    nrow = 2, 
                    ncol = 5, 
                    byrow = TRUE)
my_matrix
```

```{r}
4 * my_matrix
```

```{r}
my_values2 <- seq(from = 21, to = 30)
my_matrix2 <- matrix(my_values2, nrow = 2, byrow = TRUE)
my_matrix2
```

```{r}
my_matrix - my_matrix2
```

```{r}
# make a couple of 2 by 2 matrix 
cats <- matrix(data = c(0,4,3,1), nrow = 2, byrow =TRUE) 
dogs <- matrix(data = c(6,-3,0,2), nrow = 2, byrow = TRUE)

cats
dogs
```

```{r}
cats %*% dogs
```

## Leslies matrix example 
Create a projection matrix 
```{r}
#create matrix 
insect_leslie <- matrix(c(0,0,600, 0.2, 0, 0, 0, 0.8, 0), 
                        nrow = 3, 
                        ncol = 3, 
                        byrow = TRUE)
insect_leslie
```
specify initial conditions
```{r}
#insect lifestage population size (yr 0)
insect_y0 <- c(12000, 700, 500)
```

Find the ppulation for each lifestage at year 1
```{r}
insect_y1 <- insect_leslie %*% insect_y0
insect_y1
```
find the population for each lifestage at yr 2 
```{r}
insect_y2 <- insect_leslie %*% insect_y1
insect_y2
```
find the population for each lifestage at yr 3 
```{r}
insect_y3 <- insect_leslie %*% insect_y2
insect_y3
```
## Another leslie matrix example 

```{r}
# create projection matrix 
tree_matrix <- matrix(data = c(0,0,5000, 0.1,0,0, 0, 0.06, 0.95), 
                      nrow = 3, 
                      ncol = 3, 
                      byrow = TRUE)
tree_matrix
```

Inital conditions 
```{r}
tree_y0 <- c(5000, 0, 0)
```

```{r}
#year 1 
tree_y1 <- tree_matrix %*% tree_y0
tree_y1

#year 2
tree_y2 <- tree_matrix %*% tree_y1
tree_y2

#year 3 
tree_y3 <- tree_matrix %*% tree_y2
tree_y3

#year 4 
tree_y4 <- tree_matrix %*% tree_y3
tree_y4
```

